name: Build and push Multiwoven UI docker image to Docker Hub (ARM)

on:
  workflow_dispatch:
  push:
    tags:
      - v*

jobs:
  docker-hub-push-on-merge:
    runs-on: [self-hosted, Linux, ARM64]  # Targeting the self-hosted ARM runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Environment
        run: |
          sudo systemctl start docker
          sudo docker info

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build and push server Docker image
        run: |
          # Using Docker meta and build-push actions' functionalities via script as actions may not fully support all ARM features
          TAGS="multiwoven/multiwoven-ui:latest,multiwoven/multiwoven-ui:${{ github.ref_name }}"
          LABELS="commit=${{ github.sha }},branch=${{ github.ref }}"

          docker build -t multiwoven/multiwoven-ui:latest -t multiwoven/multiwoven-ui:${{ github.ref_name }} -f ./ui/Dockerfile ./ui
          docker push multiwoven/multiwoven-ui:latest
          docker push multiwoven/multiwoven-ui:${{ github.ref_name }}