name: frontend-docker-build (AMD)

on:
  workflow_run:
    workflows: ["frontend-ci-amd"]
    branches: [main]
    types:
      - completed

env:
  IMAGE_NAME: multiwoven/multiwoven-ui
  IMAGE_TAG: edge

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./ui
          file: ./ui/Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}-amd
            ${{ env.IMAGE_NAME }}:${{ github.sha }}-amd
          platforms: linux/amd64