name: frontend-docker-build-ARM

on:
  workflow_run:
    workflows: ["frontend-ci"]
    branches: [main]
    types:
      - completed

env:
  IMAGE_NAME: multiwoven/multiwoven-ui
  IMAGE_TAG: edge

jobs:
  build_and_push:
    runs-on: [self-hosted, ARM]  # Specify that this job runs on a self-hosted runner with the ARM label

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Docker Environment
        run: |
          sudo systemctl start docker
          sudo docker info

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build and Push Docker image
        run: |
          docker build -t ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} -t ${{ env.IMAGE_NAME }}:${{ github.sha }} -f ui/Dockerfile ./ui
          docker push ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          docker push ${{ env.IMAGE_NAME }}:${{ github.sha }}